table 'madrid_airbnb (2)'
	lineageTag: 9707e4b7-554b-4540-a4e3-eedf40873b7a

	column id
		dataType: string
		lineageTag: ec46c776-0f6a-4809-bc4b-dca80ef9598b
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 7fc2a95d-2061-4e9f-8e6f-4feff397102e
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column host_id
		dataType: int64
		formatString: 0
		lineageTag: 7bbb7303-af8c-4563-86ca-45ea015c3676
		summarizeBy: sum
		sourceColumn: host_id

		annotation SummarizationSetBy = Automatic

	column host_name
		dataType: string
		lineageTag: d5e5c6bf-9051-45fc-b211-bbf242dcb166
		summarizeBy: none
		sourceColumn: host_name

		annotation SummarizationSetBy = Automatic

	column neighbourhood_group
		dataType: string
		lineageTag: 71e2762b-1900-46d0-84dc-875e587ab227
		summarizeBy: none
		sourceColumn: neighbourhood_group

		annotation SummarizationSetBy = Automatic

	column neighbourhood
		dataType: string
		lineageTag: 73e4569d-4b4e-4c0c-9688-998a18675944
		summarizeBy: none
		sourceColumn: neighbourhood

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: int64
		formatString: 0
		lineageTag: 23fe13ee-55da-42b9-bb6a-2b0549e3d9f2
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: int64
		formatString: 0
		lineageTag: b1ab0221-1eb3-4509-a6a3-5535bc2ab286
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

	column room_type
		dataType: string
		lineageTag: 04bcfb72-0fd8-40a0-a460-ba660fad300b
		summarizeBy: none
		sourceColumn: room_type

		annotation SummarizationSetBy = Automatic

	column price
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 40d7580e-50ca-4f65-a57b-c521d377c243
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column minimum_nights
		dataType: int64
		formatString: 0
		lineageTag: 53cf65f7-3114-40e2-9d10-2a18fba45f28
		summarizeBy: sum
		sourceColumn: minimum_nights

		annotation SummarizationSetBy = Automatic

	column number_of_reviews
		dataType: int64
		formatString: 0
		lineageTag: 64270f0e-970b-46e8-8960-ae25a5d88c15
		summarizeBy: sum
		sourceColumn: number_of_reviews

		annotation SummarizationSetBy = Automatic

	column last_review
		dataType: dateTime
		formatString: Long Date
		lineageTag: 95a626b5-5d3e-48ed-a684-cbe2aebce862
		summarizeBy: none
		sourceColumn: last_review

		variation Variación
			isDefault
			relationship: f914b63d-112c-4170-b92a-4474c93183ac
			defaultHierarchy: LocalDateTable_f5df8b80-e003-4e06-9fb4-f50260aadfea.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column reviews_per_month
		dataType: string
		lineageTag: 6843b6ed-1cee-40e6-96a1-9e2b2badb60a
		summarizeBy: none
		sourceColumn: reviews_per_month

		annotation SummarizationSetBy = Automatic

	column calculated_host_listings_count
		dataType: int64
		formatString: 0
		lineageTag: 7c4b6fd6-136d-41db-9bb4-3fb4443528ae
		summarizeBy: sum
		sourceColumn: calculated_host_listings_count

		annotation SummarizationSetBy = Automatic

	column availability_365
		dataType: int64
		formatString: 0
		lineageTag: 212d0014-c393-4c69-ba3c-7b91b986a6c9
		summarizeBy: sum
		sourceColumn: availability_365

		annotation SummarizationSetBy = Automatic

	column name_limpio
		dataType: string
		lineageTag: f1691b3b-954f-4105-813d-f317afabf2f4
		summarizeBy: none
		sourceColumn: name_limpio

		annotation SummarizationSetBy = Automatic

	partition 'madrid_airbnb (2)' = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\Don Bosco\Desktop\bootcamp-da-p2\DA-project-Power-BI-Analysis-Grupo-5\Data\madrid_airbnb.csv"),[Delimiter=",", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", type text}, {"name", type text}, {"host_id", type text}, {"host_name", type text}, {"neighbourhood_group", type text}, {"neighbourhood", type text}, {"latitude", type text}, {"longitude", Int64.Type}, {"room_type", type text}, {"price", type text}, {"minimum_nights", Int64.Type}, {"number_of_reviews", Int64.Type}, {"last_review", type text}, {"reviews_per_month", type text}, {"calculated_host_listings_count", Int64.Type}, {"availability_365", Int64.Type}, {"", Int64.Type}}),
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each [id] <> null and [id] <> ""),
				    #"Filas filtradas1" = Table.SelectRows(#"Filas filtradas", each [host_id] <> null and [host_id] <> ""),
				    #"Filas filtradas2" = Table.SelectRows(#"Filas filtradas1", each ([host_name] <> null and [host_name] <> "") and ([id] <> " newly decor.Chuecasheart. Patio.""" and [id] <> "HISTORICAL")),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Filas filtradas2",{{"host_id", Int64.Type}}),
				    #"Errores quitados" = Table.RemoveRowsWithErrors(#"Tipo cambiado1", {"host_id"}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Errores quitados",{{"latitude", Int64.Type}, {"price", Currency.Type}, {"last_review", type date}}),
				    #"Filas filtradas3" = Table.SelectRows(#"Tipo cambiado2", each [last_review] <> null and [last_review] <> ""),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Filas filtradas3",{""}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas quitadas", "name_limpio", each Text.Select([name], {"A".."Z", "a".."z", "0".."9", " ", ".", ",", "-", "&", "ñ", "Ñ", "á", "é", "í", "ó", "ú", "Á", "É", "Í", "Ó", "Ú"}))
				in
				    #"Personalizada agregada"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

