table madrid_airbnb
	lineageTag: 363f592d-fdbc-41a2-b76c-19354a5a3f4a

	column id
		dataType: string
		lineageTag: acb0ea0d-c55c-4ca6-b2d9-00cd9b15aa61
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 65f65913-cf47-475a-91f1-3a4c7c54b386
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column host_id
		dataType: string
		lineageTag: 9fcc13ff-48c5-4977-8378-baadaeb48c9e
		summarizeBy: none
		sourceColumn: host_id

		annotation SummarizationSetBy = Automatic

	column host_name
		dataType: string
		lineageTag: 9fd7532c-036f-4695-bff8-6a272b5446a9
		summarizeBy: none
		sourceColumn: host_name

		annotation SummarizationSetBy = Automatic

	column neighbourhood_group
		dataType: string
		lineageTag: 1bbd5900-25cb-4db1-b82f-acbc9ba00d70
		summarizeBy: none
		sourceColumn: neighbourhood_group

		annotation SummarizationSetBy = Automatic

	column neighbourhood
		dataType: string
		lineageTag: 2e7821be-4ee5-4e79-abea-e18ac0b5f878
		summarizeBy: none
		sourceColumn: neighbourhood

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: int64
		formatString: 0
		lineageTag: 92831af5-054d-4629-8489-f6476f8d9eb6
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: int64
		formatString: 0
		lineageTag: 62136641-db7c-4ad0-8f1b-641befd26204
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

	column room_type
		dataType: string
		lineageTag: 5f9e6ee8-90a0-4b31-9ac0-0882947ff6dc
		summarizeBy: none
		sourceColumn: room_type

		annotation SummarizationSetBy = Automatic

	column price
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 25e197a3-264c-494a-8b25-41d521d3df96
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column minimum_nights
		dataType: int64
		formatString: 0
		lineageTag: 965ea180-72ad-4dd8-943f-224961731a41
		summarizeBy: sum
		sourceColumn: minimum_nights

		annotation SummarizationSetBy = Automatic

	column number_of_reviews
		dataType: int64
		formatString: 0
		lineageTag: dda6848f-f112-4494-8e83-5f7862046362
		summarizeBy: sum
		sourceColumn: number_of_reviews

		annotation SummarizationSetBy = Automatic

	column last_review
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6f43cd23-6fc8-4e17-a03b-c40e289a174f
		summarizeBy: none
		sourceColumn: last_review

		variation Variación
			isDefault
			relationship: 4f494e1a-5d77-4faf-a2eb-71bd691f00f7
			defaultHierarchy: LocalDateTable_224190a3-ffed-4171-8bc3-57cd458a690a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column reviews_per_month
		dataType: string
		lineageTag: 6891f8c4-e1e6-4e5d-a20f-1e32516b4c05
		summarizeBy: none
		sourceColumn: reviews_per_month

		annotation SummarizationSetBy = Automatic

	column calculated_host_listings_count
		dataType: int64
		formatString: 0
		lineageTag: 0d362ae5-dbc6-4b08-b12f-8dfbd36994ee
		summarizeBy: sum
		sourceColumn: calculated_host_listings_count

		annotation SummarizationSetBy = Automatic

	column availability_365
		dataType: int64
		formatString: 0
		lineageTag: 5bc2f562-87fd-4705-8ebc-df3e4780127a
		summarizeBy: sum
		sourceColumn: availability_365

		annotation SummarizationSetBy = Automatic

	column name_limpio
		dataType: string
		lineageTag: fa776e5f-ffaa-40c8-ad4e-f5f0a15ecfe9
		summarizeBy: none
		sourceColumn: name_limpio

		annotation SummarizationSetBy = Automatic

	partition madrid_airbnb = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\Don Bosco\Desktop\bootcamp-da-p2\DA-project-Power-BI-Analysis-Grupo-5\Data\madrid_airbnb.csv"),[Delimiter=",", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", type text}, {"name", type text}, {"host_id", type text}, {"host_name", type text}, {"neighbourhood_group", type text}, {"neighbourhood", type text}, {"latitude", type text}, {"longitude", Int64.Type}, {"room_type", type text}, {"price", type text}, {"minimum_nights", Int64.Type}, {"number_of_reviews", Int64.Type}, {"last_review", type text}, {"reviews_per_month", type text}, {"calculated_host_listings_count", Int64.Type}, {"availability_365", Int64.Type}, {"", Int64.Type}}),
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each [id] <> null and [id] <> ""),
				    #"Filas filtradas1" = Table.SelectRows(#"Filas filtradas", each [host_id] <> null and [host_id] <> ""),
				    #"Filas filtradas2" = Table.SelectRows(#"Filas filtradas1", each [host_name] <> null and [host_name] <> ""),
				    #"Errores quitados" = Table.RemoveRowsWithErrors(#"Filas filtradas2", {"longitude"}),
				    #"Filas filtradas3" = Table.SelectRows(#"Errores quitados", each [last_review] <> null and [last_review] <> ""),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Filas filtradas3",{""}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columnas quitadas",{{"longitude", Int64.Type}, {"latitude", Int64.Type}, {"price", Currency.Type}}),
				    #"Filas filtradas4" = Table.SelectRows(#"Tipo cambiado1", each ([id] <> "HISTORICAL")),
				    #"Personalizada agregada" = Table.AddColumn(#"Filas filtradas4", "name_limpio", each Text.Select([name], {"A".."Z", "a".."z", "0".."9", " ", ".", ",", "-", "ñ", "Ñ", "á", "é", "í", "ó", "ú", "Á", "É", "Í", "Ó", "Ú", "&"})),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Personalizada agregada",{"id", "name", "name_limpio", "host_id", "host_name", "neighbourhood_group", "neighbourhood", "latitude", "longitude", "room_type", "price", "minimum_nights", "number_of_reviews", "last_review", "reviews_per_month", "calculated_host_listings_count", "availability_365"}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columnas reordenadas",{{"last_review", type date}})
				in
				    #"Tipo cambiado2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

