table Append1
	lineageTag: eaf395a6-c099-44b4-bd54-e74cb20549cc

	column id
		dataType: string
		lineageTag: 0919cd5b-1896-437e-87ec-89dacb7d0cfb
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: ea511580-39c9-45f4-a301-3fba360c668b
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column host_id
		dataType: string
		lineageTag: 1191ee37-44d2-49e2-b7be-f36cfed42cfd
		summarizeBy: none
		sourceColumn: host_id

		annotation SummarizationSetBy = Automatic

	column host_name
		dataType: string
		lineageTag: 3cff4b5d-268d-4444-8e60-ee24c8e3e96e
		summarizeBy: none
		sourceColumn: host_name

		annotation SummarizationSetBy = Automatic

	column neighbourhood
		dataType: string
		lineageTag: 3f72f132-0592-49d0-8d46-d58890ed1436
		summarizeBy: none
		sourceColumn: neighbourhood

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		formatString: 0
		lineageTag: 87276964-7e77-46d6-84fb-4825dcb1d4f2
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		formatString: 0
		lineageTag: 405955e6-0b60-4d00-aae1-7ad8bcce6227
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

	column room_type
		dataType: string
		lineageTag: e553b4c2-4179-4b4b-8a22-6745a44940c2
		summarizeBy: none
		sourceColumn: room_type

		annotation SummarizationSetBy = Automatic

	column price
		dataType: string
		lineageTag: ba1a24c2-3eac-4e90-bd90-8dca2761a336
		summarizeBy: none
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	column minimum_nights
		dataType: string
		lineageTag: 40cb4fbb-0916-4333-bbf0-89e583cddeb5
		summarizeBy: none
		sourceColumn: minimum_nights

		annotation SummarizationSetBy = Automatic

	column number_of_reviews
		dataType: string
		lineageTag: 67d93bce-5e30-4f94-b976-391689d48fe4
		summarizeBy: none
		sourceColumn: number_of_reviews

		annotation SummarizationSetBy = Automatic

	column last_review
		dataType: string
		lineageTag: 4e73a288-7bc5-461c-a97f-4bb07ab4cb89
		summarizeBy: none
		sourceColumn: last_review

		annotation SummarizationSetBy = Automatic

	column reviews_per_month
		dataType: string
		lineageTag: c6e4bb05-890e-4f37-b3e5-ffa9912455aa
		summarizeBy: none
		sourceColumn: reviews_per_month

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: c03fb14b-2354-4ac5-9551-cb33de93549c
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column name_limpio
		dataType: string
		lineageTag: b926c254-0d04-4e3b-be69-e412fb02e10b
		summarizeBy: none
		sourceColumn: name_limpio

		annotation SummarizationSetBy = Automatic

	column calculated_host_listings_count
		dataType: string
		lineageTag: d16fd279-e587-4e3f-92ed-4107c8ade782
		summarizeBy: none
		sourceColumn: calculated_host_listings_count

		annotation SummarizationSetBy = Automatic

	column availability_365
		dataType: string
		lineageTag: 3964ff26-53f1-4d26-8d18-9438bd102cbc
		summarizeBy: none
		sourceColumn: availability_365

		annotation SummarizationSetBy = Automatic

	partition Append1 = m
		mode: import
		source =
				let
				    Source = Table.Combine({tokyo_airbnb, madrid_airbnb, london_airbnb, NY_airbnb, milan_airbnb, sydney_airbnb}),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"neighbourhood_group"}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Removed Columns", {"id"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Errors", each [host_id] <> null and [host_id] <> ""),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [host_name] <> null and [host_name] <> ""),
				    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each ([last_review] <> null and [last_review] <> ""))
				in
				    #"Filtered Rows2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

