table dim_neighbourhood
	isHidden
	lineageTag: af1ba707-4bb4-4099-96e4-f1e75fffaa91

	column neighbourhood
		dataType: string
		isHidden
		lineageTag: ae3d44b7-4e76-4269-8064-f713ac1ef09d
		summarizeBy: none
		sourceColumn: neighbourhood

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		isHidden
		lineageTag: 437036aa-ab63-45bb-b45b-d004ba047650
		summarizeBy: none
		sourceColumn: city

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_neighbourhood
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9298a50c-9618-4350-8904-083f939ff9fd
		summarizeBy: none
		sourceColumn: id_neighbourhood

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 88b73957-f3a7-439e-ae77-5134f1142012
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: c93a0b64-cfd1-4fe9-bab3-4ff0827a4265
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dim_neighbourhood = m
		mode: import
		source =
				let
				    Cols      = Table.SelectColumns(base_combinada, {"neighbourhood", "city", "latitude", "longitude"}),
				    Distintos = Table.Distinct(Cols, {"neighbourhood"}),
				    Filtrados = Table.SelectRows(Distintos, each [neighbourhood] <> "" and [neighbourhood] <> null),
				    Indexado  = Table.AddIndexColumn(Filtrados, "id_neighbourhood", 1, 1, Int64.Type)
				in
				    Indexado

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

