table dim_city
	lineageTag: 1594e8fe-2644-4376-b9f3-96c4331d665f

	column city
		dataType: string
		lineageTag: 3e8fec97-3b25-423c-a759-0b89b3d5b782
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column id_city
		dataType: int64
		formatString: 0
		lineageTag: de5eb722-cf8c-4265-bcb5-a4c5c5a64f4c
		summarizeBy: sum
		sourceColumn: id_city

		annotation SummarizationSetBy = Automatic

	partition dim_city = m
		mode: import
		source = ```
				let
				    // 1. Cargamos el archivo utilizando QuoteStyle.Csv para que asimile perfectamente las comas internas de los nombres
				    Origen = Csv.Document(File.Contents("C:\Users\crist\Desktop\DataAnalyst_Ana\DA-project-Power-BI-Analysis-Grupo-5\data\sydney_airbnb.csv"), [Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.Csv]),
				    
				    // 2. Subimos la primera fila como los títulos de las columnas
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				
				    // 3. Convertir Latitud usando región de EE.UU. (acepta puntos como decimales)
				    #"Tipo cambiado con configuración regional" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"latitude", type number}}, "en-US"),
				
				    // 4. Si la latitud dio error, se reemplaza por un 0
				    #"Errores reemplazados" = Table.ReplaceErrorValues(#"Tipo cambiado con configuración regional", {{"latitude", 0}}),
				
				    // 5. Convertir Longitud usando región de EE.UU.
				    #"Tipo cambiado con configuración regional1" = Table.TransformColumnTypes(#"Errores reemplazados", {{"longitude", type number}}, "en-US"),
				
				    // 6. Si la longitud dio error, se reemplaza por un 0
				    #"Errores reemplazados1" = Table.ReplaceErrorValues(#"Tipo cambiado con configuración regional1", {{"longitude", 0}}),
				
				    // 7. Limpieza de textos en un solo paso eficiente (Poner en mayúscula cada palabra, quitar espacios y caracteres invisibles)
				    #"Textos limpios" = Table.TransformColumns(#"Errores reemplazados1", {
				        {"name", each Text.Proper(Text.Trim(Text.Clean(Text.From(_)))), type text},
				        {"host_name", each Text.Proper(Text.Trim(Text.Clean(Text.From(_)))), type text},
				        {"neighbourhood", each Text.Proper(Text.Trim(Text.Clean(Text.From(_)))), type text},
				        {"room_type", each Text.Proper(Text.Trim(Text.Clean(Text.From(_)))), type text}
				    }),
				
				    // 8. Convertir columnas numéricas de manera segura (si encuentra texto pone NULL) y limpiar el signo $ y comas del precio
				    #"room_type" = Table.TransformColumns(#"Textos limpios", {
				        {"availability_365", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"calculated_host_listings_count", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"number_of_reviews", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"minimum_nights", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"price", each try Int64.From(Text.Replace(Text.Replace(Text.Replace(Text.Trim(Text.From(_)), "$", ""), ",", ""), ".", "")) otherwise null, Int64.Type},
				        {"host_id", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"id", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type}
				    }),
				
				    // 9. Convertir reseñas por mes usando región de EE.UU.
				    #"Tipo_EEUU_reviews_per_month" = Table.TransformColumnTypes(#"room_type", {{"reviews_per_month", type number}}, "en-US"),
				
				    // 10. Si la reseña da error, se reemplaza por 0
				    #"Errores_reviews_per_month" = Table.ReplaceErrorValues(#"Tipo_EEUU_reviews_per_month", {{"reviews_per_month", 0}}),
				
				    // 11. Convertir las reseñas finales a número entero
				    #"tipo-entero_reviews_per_month" = Table.TransformColumnTypes(#"Errores_reviews_per_month", {{"reviews_per_month", Int64.Type}}),
				
				    // 12. Convertir de manera segura la columna de fechas (si falla pone NULL)
				    #"Tipo cambiado" = Table.TransformColumns(#"tipo-entero_reviews_per_month", {
				        {"last_review", each try Date.From(_) otherwise null, type date}
				    }),
				
				    // 13. Agregar la columna final identificando que pertenece a la ciudad de sydney
				    #"Columna ciudad agregada" = Table.AddColumn(#"Tipo cambiado", "ciudad", each "sydney", type text),
				    
				    #"Filas filtradas" = Table.SelectRows(#"Columna ciudad agregada", each true),
				    
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Filas filtradas",{{"ciudad", Text.Proper, type text}}),
				    
				    #"Valor reemplazado" = Table.ReplaceValue(#"Poner En Mayúsculas Cada Palabra","",null,Replacer.ReplaceValue,{"neighbourhood_group"}),
				    
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Valor reemplazado",{{"ciudad", "city"}}),
				    
				    // CORREGIDO: Ahora sí se apoya en #"Columnas con nombre cambiado" y se le quitó la coma final
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "name_limpio", each Text.Select([name], {"A".."Z", "a".."z", "0".."9", " ", ".", ",", "-", "ñ", "Ñ", "á", "é", "í", "ó", "ú", "Á", "É", "Í", "Ó", "Ú", "&"})),
				    #"Consulta anexada" = Table.Combine({#"Personalizada agregada", madrid_airbnb, london_airbnb, NY_airbnb, milan_airbnb, tokyo_airbnb}),
				    #"Poner En Mayúsculas Cada Palabra1" = Table.TransformColumns(#"Consulta anexada",{{"room_type", Text.Proper, type text}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Poner En Mayúsculas Cada Palabra1", {"room_type"}, dim_room_Type, {"room_type"}, "dim_room_Type", JoinKind.LeftOuter),
				    #"Se expandió dim_room_Type" = Table.ExpandTableColumn(#"Consultas combinadas", "dim_room_Type", {"id_roomType"}, {"dim_room_Type.id_roomType"}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Se expandió dim_room_Type",{"id", "name", "host_id", "host_name", "room_type", "price", "minimum_nights", "number_of_reviews", "last_review", "calculated_host_listings_count", "availability_365", "name_limpio", "dim_room_Type.id_roomType", "reviews_per_month"}),
				    #"Duplicados quitados" = Table.Distinct(#"Columnas quitadas", {"neighbourhood"}),
				    #"Índice agregado" = Table.AddIndexColumn(#"Duplicados quitados", "Índice", 1, 1, Int64.Type),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Índice agregado",{{"Índice", "id_neighbourhood"}}),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Columnas con nombre cambiado1",{"city"}),
				    #"Duplicados quitados1" = Table.Distinct(#"Otras columnas quitadas"),
				    #"Índice agregado1" = Table.AddIndexColumn(#"Duplicados quitados1", "Índice", 1, 1, Int64.Type),
				    #"Columnas con nombre cambiado2" = Table.RenameColumns(#"Índice agregado1",{{"Índice", "id_city"}})
				in
				    #"Columnas con nombre cambiado2"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

