table dim_roomType
	lineageTag: 09b35176-ccf2-4e83-a3b5-f2cb273b944d

	column room_type
		dataType: string
		lineageTag: cd41aa86-a29a-445a-8dda-528499d24e8a
		summarizeBy: none
		sourceColumn: room_type

		annotation SummarizationSetBy = Automatic

	column roomtype_key
		dataType: int64
		formatString: 0
		lineageTag: b8cc75c0-f182-4a23-a150-f31a8c22cdd4
		summarizeBy: sum
		sourceColumn: roomtype_key

		annotation SummarizationSetBy = Automatic

	partition dim_roomType = m
		mode: import
		source =
				let
				    Origen = fact_listings,
				    #"Otras columnas quitadas" = Table.SelectColumns(Origen,{"room_type"}),
				    #"Duplicados quitados" = Table.Distinct(#"Otras columnas quitadas"),
				    #"Filas filtradas" = Table.SelectRows(#"Duplicados quitados", each ([room_type] <> "")),
				    #"Índice agregado" = Table.AddIndexColumn(#"Filas filtradas", "Índice", 1, 1, Int64.Type),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Índice agregado",{{"Índice", "roomtype_key"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

