table dim_date
	lineageTag: b2ea870e-b7b9-4a28-aa3a-22b0f34aff5c

	column last_review
		dataType: dateTime
		formatString: Long Date
		lineageTag: c7d121e4-6518-4720-bd8e-4b9c5af0da3f
		summarizeBy: none
		sourceColumn: last_review

		variation Variación
			isDefault
			relationship: 2b0b4d94-eb2b-4893-ade5-e47fd1fd31b7
			defaultHierarchy: LocalDateTable_b45107fd-d3ad-48bf-a93a-d4bbd8662b39.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column id_date
		dataType: int64
		formatString: 0
		lineageTag: 2b5986c1-2b66-43a4-9dea-12d48dbdc4ec
		summarizeBy: none
		sourceColumn: id_date

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Cols      = Table.SelectColumns(base_combinada, {"last_review"}),
				    Filtrados = Table.SelectRows(Cols, each [last_review] <> null),
				    Distintos = Table.Distinct(Filtrados),
				    Indexado  = Table.AddIndexColumn(Distintos, "id_date", 1, 1, Int64.Type)
				in
				    Indexado

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

