table dimension_house
	lineageTag: 24e11543-54c7-4721-98a7-0b504201c221

	column id
		dataType: string
		lineageTag: 131da7ab-a2a7-409c-8a3b-4dcca14ddee3
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: e6da4c70-7b81-48d8-96ab-2bc9c6996331
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column room_type
		dataType: string
		lineageTag: 4fdd6520-ead0-4192-8646-3d5d6c5b8357
		summarizeBy: none
		sourceColumn: room_type

		annotation SummarizationSetBy = Automatic

	column price
		dataType: string
		lineageTag: be6fa764-64a5-42bb-ac7f-bb8f4c7dfb38
		summarizeBy: none
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	column minimum_nights
		dataType: string
		lineageTag: e222554f-5e6f-4eb8-9258-b7c7d25d7d3d
		summarizeBy: none
		sourceColumn: minimum_nights

		annotation SummarizationSetBy = Automatic

	column number_of_reviews
		dataType: string
		lineageTag: e947640d-4df3-414d-8f26-2b5434728e94
		summarizeBy: none
		sourceColumn: number_of_reviews

		annotation SummarizationSetBy = Automatic

	column last_review
		dataType: string
		lineageTag: 961c630b-1a03-4cc8-8371-6a3db28dc14d
		summarizeBy: none
		sourceColumn: last_review

		annotation SummarizationSetBy = Automatic

	column reviews_per_month
		dataType: string
		lineageTag: d80c8af2-57aa-4a7f-af36-6b8bf364b310
		summarizeBy: none
		sourceColumn: reviews_per_month

		annotation SummarizationSetBy = Automatic

	column name_limpio
		dataType: string
		lineageTag: f42656aa-1577-4a87-8f30-b3200075f03f
		summarizeBy: none
		sourceColumn: name_limpio

		annotation SummarizationSetBy = Automatic

	column availability_365
		dataType: string
		lineageTag: 7f810eac-2398-4df1-9af1-e75b4b363fec
		summarizeBy: none
		sourceColumn: availability_365

		annotation SummarizationSetBy = Automatic

	partition dimension_house = m
		mode: import
		source =
				let
				    Origen = Table_Fact,
				    #"Columnas quitadas" = Table.RemoveColumns(Origen,{"host_name", "host_id", "calculated_host_listings_count", "", "neighbourhood", "latitude", "longitude", "city"})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

