table dimension_geografic
	lineageTag: b2d1105e-430e-47c2-a638-de9184ccb76b

	column id
		dataType: string
		lineageTag: 9e23ca12-0d14-4985-886e-918d069bf2ff
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: ca0b6e08-0881-4449-8135-18c4096f3fec
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 8d82771f-d0e6-450f-8e41-e948e5bc3557
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column city
		dataType: string
		lineageTag: 1418eebb-9723-47c7-80d6-4b09bcda632d
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	partition dimension_geografic = m
		mode: import
		source =
				let
				    Origen = Table_Fact,
				    #"Columnas quitadas" = Table.RemoveColumns(Origen,{"name", "host_id", "host_name", "neighbourhood", "room_type", "price", "minimum_nights", "number_of_reviews", "last_review", "reviews_per_month", "name_limpio", "calculated_host_listings_count", "availability_365", ""})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

