table dimension_host
	lineageTag: d8d29ee2-659e-4c1a-9988-e4b5d828f890

	column id
		dataType: string
		lineageTag: 6e44bf2f-21b1-41f6-ae4c-834d958e852b
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column host_id
		dataType: string
		lineageTag: e40e1e66-c965-4d12-b3f2-eff6b81781dd
		summarizeBy: none
		sourceColumn: host_id

		annotation SummarizationSetBy = Automatic

	column host_name
		dataType: string
		lineageTag: 3e7a00a3-a5f0-49e9-b83d-e7135bd27fc6
		summarizeBy: none
		sourceColumn: host_name

		annotation SummarizationSetBy = Automatic

	column calculated_host_listings_count
		dataType: string
		lineageTag: f6c5c57d-478d-4e49-b450-2c961bf7d3c6
		summarizeBy: none
		sourceColumn: calculated_host_listings_count

		annotation SummarizationSetBy = Automatic

	partition dimension_host = m
		mode: import
		source =
				let
				    Origen = Table_Fact,
				    #"Columnas quitadas" = Table.RemoveColumns(Origen,{"name", "neighbourhood", "latitude", "longitude", "room_type", "price", "minimum_nights", "number_of_reviews", "last_review", "reviews_per_month", "city", "name_limpio", "availability_365", ""})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

