table fact_listings
	lineageTag: 37206f3e-c3e0-4819-9d02-f57268633441

	column id
		dataType: string
		lineageTag: 2ecf487a-6a02-4a29-bfca-174ea4393022
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column host_id
		dataType: string
		lineageTag: 75cc657f-f543-4208-9dfa-d99e3dc2ab84
		summarizeBy: none
		sourceColumn: host_id

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		lineageTag: f9cb6b79-9479-4d51-af74-39ee8cd98c06
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column minimum_nights
		dataType: int64
		formatString: 0
		lineageTag: 0d85a693-9e7c-4f85-ac9f-969d87f5452d
		summarizeBy: sum
		sourceColumn: minimum_nights

		annotation SummarizationSetBy = Automatic

	column number_of_reviews
		dataType: int64
		formatString: 0
		lineageTag: 20ac221c-f8f7-4c04-a53e-a709e925c03d
		summarizeBy: sum
		sourceColumn: number_of_reviews

		annotation SummarizationSetBy = Automatic

	column reviews_per_month
		dataType: double
		lineageTag: 830f0c05-56d9-4239-bb85-23b285fe1428
		summarizeBy: sum
		sourceColumn: reviews_per_month

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'dim_room_Type.id_roomType'
		dataType: int64
		formatString: 0
		lineageTag: b7dfe410-8e8b-41fc-b184-d0a6746a0c51
		summarizeBy: sum
		sourceColumn: dim_room_Type.id_roomType

		annotation SummarizationSetBy = Automatic

	column 'dim_city.id_neighbourhood'
		dataType: int64
		formatString: 0
		lineageTag: d9728b2a-dd7d-4600-b288-9144b1c37821
		summarizeBy: none
		sourceColumn: dim_city.id_neighbourhood

		annotation SummarizationSetBy = Automatic

	column 'dim_date.id_date'
		dataType: int64
		formatString: 0
		lineageTag: 65054ca1-9480-49e5-9e50-ec19f981c5e8
		summarizeBy: none
		sourceColumn: dim_date.id_date

		annotation SummarizationSetBy = Automatic

	partition fact_listings = m
		mode: import
		source = ```
				let
				    // 1. Cargamos el archivo utilizando QuoteStyle.Csv para que asimile perfectamente las comas internas de los nombres
				    Origen = Csv.Document(File.Contents("C:\Users\crist\Desktop\DataAnalyst_Ana\DA-project-Power-BI-Analysis-Grupo-5\data\sydney_airbnb.csv"), [Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.Csv]),
				    
				    // 2. Subimos la primera fila como los tГӯtulos de las columnas
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				
				    // 3. Convertir Latitud usando regiГіn de EE.UU. (acepta puntos como decimales)
				    #"Tipo cambiado con configuraciГіn regional" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"latitude", type number}}, "en-US"),
				
				    // 4. Si la latitud dio error, se reemplaza por un 0
				    #"Errores reemplazados" = Table.ReplaceErrorValues(#"Tipo cambiado con configuraciГіn regional", {{"latitude", 0}}),
				
				    // 5. Convertir Longitud usando regiГіn de EE.UU.
				    #"Tipo cambiado con configuraciГіn regional1" = Table.TransformColumnTypes(#"Errores reemplazados", {{"longitude", type number}}, "en-US"),
				
				    // 6. Si la longitud dio error, se reemplaza por un 0
				    #"Errores reemplazados1" = Table.ReplaceErrorValues(#"Tipo cambiado con configuraciГіn regional1", {{"longitude", 0}}),
				
				    // 7. Limpieza de textos en un solo paso eficiente (Poner en mayГәscula cada palabra, quitar espacios y caracteres invisibles)
				    #"Textos limpios" = Table.TransformColumns(#"Errores reemplazados1", {
				        {"name", each Text.Proper(Text.Trim(Text.Clean(Text.From(_)))), type text},
				        {"host_name", each Text.Proper(Text.Trim(Text.Clean(Text.From(_)))), type text},
				        {"neighbourhood", each Text.Proper(Text.Trim(Text.Clean(Text.From(_)))), type text},
				        {"room_type", each Text.Proper(Text.Trim(Text.Clean(Text.From(_)))), type text}
				    }),
				
				    // 8. Convertir columnas numГ©ricas de manera segura (si encuentra texto pone NULL) y limpiar el signo $ y comas del precio
				    #"room_type" = Table.TransformColumns(#"Textos limpios", {
				        {"availability_365", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"calculated_host_listings_count", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"number_of_reviews", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"minimum_nights", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"price", each try Int64.From(Text.Replace(Text.Replace(Text.Replace(Text.Trim(Text.From(_)), "$", ""), ",", ""), ".", "")) otherwise null, Int64.Type},
				        {"host_id", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"id", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type}
				    }),
				
				    // 9. Convertir reseГұas por mes usando regiГіn de EE.UU.
				    #"Tipo_EEUU_reviews_per_month" = Table.TransformColumnTypes(#"room_type", {{"reviews_per_month", type number}}, "en-US"),
				
				    // 10. Si la reseГұa da error, se reemplaza por 0
				    #"Errores_reviews_per_month" = Table.ReplaceErrorValues(#"Tipo_EEUU_reviews_per_month", {{"reviews_per_month", 0}}),
				
				    // 11. Convertir las reseГұas finales a nГәmero entero
				    #"tipo-entero_reviews_per_month" = Table.TransformColumnTypes(#"Errores_reviews_per_month", {{"reviews_per_month", Int64.Type}}),
				
				    // 12. Convertir de manera segura la columna de fechas (si falla pone NULL)
				    #"Tipo cambiado" = Table.TransformColumns(#"tipo-entero_reviews_per_month", {
				        {"last_review", each try Date.From(_) otherwise null, type date}
				    }),
				
				    // 13. Agregar la columna final identificando que pertenece a la ciudad de sydney
				    #"Columna ciudad agregada" = Table.AddColumn(#"Tipo cambiado", "ciudad", each "sydney", type text),
				    
				    #"Filas filtradas" = Table.SelectRows(#"Columna ciudad agregada", each true),
				    
				    #"Poner En MayГәsculas Cada Palabra" = Table.TransformColumns(#"Filas filtradas",{{"ciudad", Text.Proper, type text}}),
				    
				    #"Valor reemplazado" = Table.ReplaceValue(#"Poner En MayГәsculas Cada Palabra","",null,Replacer.ReplaceValue,{"neighbourhood_group"}),
				    
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Valor reemplazado",{{"ciudad", "city"}}),
				    
				    // CORREGIDO: Ahora sГӯ se apoya en #"Columnas con nombre cambiado" y se le quitГі la coma final
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "name_limpio", each Text.Select([name], {"A".."Z", "a".."z", "0".."9", " ", ".", ",", "-", "Гұ", "Г‘", "ГЎ", "Г©", "Гӯ", "Гі", "Гә", "ГҒ", "Гү", "ГҚ", "Г“", "Гҡ", "&"})),
				    #"Consulta anexada" = Table.Combine({#"Personalizada agregada", madrid_airbnb, london_airbnb, NY_airbnb, milan_airbnb, tokyo_airbnb}),
				    #"Poner En MayГәsculas Cada Palabra1" = Table.TransformColumns(#"Consulta anexada",{{"room_type", Text.Proper, type text}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Poner En MayГәsculas Cada Palabra1", {"room_type"}, dim_room_Type, {"room_type"}, "dim_room_Type", JoinKind.LeftOuter),
				    #"Se expandiГі dim_room_Type" = Table.ExpandTableColumn(#"Consultas combinadas", "dim_room_Type", {"id_roomType"}, {"dim_room_Type.id_roomType"}),
				    #"Consultas combinadas1" = Table.NestedJoin(#"Se expandiГі dim_room_Type", {"neighbourhood"}, dim_neighbourhood, {"neighbourhood"}, "dim_city", JoinKind.LeftOuter),
				    #"Consultas combinadas2" = Table.NestedJoin(#"Consultas combinadas1", {"last_review"}, dim_date, {"last_review"}, "dim_date", JoinKind.LeftOuter),
				    #"Se expandiГі dim_city" = Table.ExpandTableColumn(#"Consultas combinadas2", "dim_city", {"id_neighbourhood"}, {"dim_city.id_neighbourhood"}),
				    #"Se expandiГі dim_date" = Table.ExpandTableColumn(#"Se expandiГі dim_city", "dim_date", {"id_date"}, {"dim_date.id_date"}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Se expandiГі dim_date",{"name", "host_name", "neighbourhood_group", "neighbourhood", "latitude", "longitude", "room_type", "last_review", "calculated_host_listings_count", "availability_365", "city", "name_limpio"})
				in
				    #"Columnas quitadas"
				```

	annotation PBI_NavigationStepName = NavegaciГіn

	annotation PBI_ResultType = Table

