table madrid_airbnb
	lineageTag: b1c64bac-333d-4051-a6f1-35c0cab27666

	column id
		dataType: string
		lineageTag: 81e3533b-3a15-46fb-bece-c51f10b3cdb4
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 4f387a5a-5369-4c34-956f-1e8813a41b70
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column name_limpio
		dataType: string
		lineageTag: 7f92f190-804e-4d8c-9931-bb6e2cfe2ac0
		summarizeBy: none
		sourceColumn: name_limpio

		annotation SummarizationSetBy = Automatic

	column host_id
		dataType: string
		lineageTag: 0267ffb6-e4ad-423b-b4de-94a8c6238100
		summarizeBy: none
		sourceColumn: host_id

		annotation SummarizationSetBy = Automatic

	column host_name
		dataType: string
		lineageTag: 3959d470-2bbd-40aa-8958-053632b6e34b
		summarizeBy: none
		sourceColumn: host_name

		annotation SummarizationSetBy = Automatic

	column neighbourhood_group
		dataType: string
		lineageTag: 3f0475cb-5399-4e61-b8e5-7ffaddc219de
		summarizeBy: none
		sourceColumn: neighbourhood_group

		annotation SummarizationSetBy = Automatic

	column neighbourhood
		dataType: string
		lineageTag: cd1fe14d-43c7-4058-b867-6acd3da95168
		summarizeBy: none
		sourceColumn: neighbourhood

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: int64
		formatString: 0
		lineageTag: 619c69c3-ae6d-4e21-9ebd-9e31325c325a
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: int64
		formatString: 0
		lineageTag: 992d34ec-c286-4704-92f3-6733b6c625a4
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

	column room_type
		dataType: string
		lineageTag: 8f59c61a-acda-4f27-bcfc-b77b768244a5
		summarizeBy: none
		sourceColumn: room_type

		annotation SummarizationSetBy = Automatic

	column price
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 40d4da97-33e7-46e5-915a-33bfe3554d38
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column minimum_nights
		dataType: int64
		formatString: 0
		lineageTag: e02c6726-797b-4de3-8171-e84087b4168d
		summarizeBy: sum
		sourceColumn: minimum_nights

		annotation SummarizationSetBy = Automatic

	column number_of_reviews
		dataType: int64
		formatString: 0
		lineageTag: be354626-25ce-47bf-8266-25d5b9959535
		summarizeBy: sum
		sourceColumn: number_of_reviews

		annotation SummarizationSetBy = Automatic

	column last_review
		dataType: dateTime
		formatString: Long Date
		lineageTag: cd1cbaad-70da-40fb-bd47-5dce7ec35343
		summarizeBy: none
		sourceColumn: last_review

		variation Variación
			isDefault
			relationship: 2e8ae6a1-118e-42c3-86c5-e3098d75787d
			defaultHierarchy: LocalDateTable_e013f620-fd16-4c2e-9533-988287e4ed74.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column reviews_per_month
		dataType: string
		lineageTag: e62db97c-a7f1-46a5-836d-f52d6a51c8ee
		summarizeBy: none
		sourceColumn: reviews_per_month

		annotation SummarizationSetBy = Automatic

	column calculated_host_listings_count
		dataType: int64
		formatString: 0
		lineageTag: 7ef12548-617c-49a1-b670-36707dccef46
		summarizeBy: sum
		sourceColumn: calculated_host_listings_count

		annotation SummarizationSetBy = Automatic

	column availability_365
		dataType: int64
		formatString: 0
		lineageTag: a331ed80-e004-4283-9208-c232c5ac13b2
		summarizeBy: sum
		sourceColumn: availability_365

		annotation SummarizationSetBy = Automatic

	partition madrid_airbnb = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\Don Bosco\Desktop\bootcamp-da-p2\DA-project-Power-BI-Analysis-Grupo-5\Data\madrid_airbnb.csv"),[Delimiter=",", Columns=17, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", type text}, {"name", type text}, {"host_id", type text}, {"host_name", type text}, {"neighbourhood_group", type text}, {"neighbourhood", type text}, {"latitude", type text}, {"longitude", Int64.Type}, {"room_type", type text}, {"price", type text}, {"minimum_nights", Int64.Type}, {"number_of_reviews", Int64.Type}, {"last_review", type text}, {"reviews_per_month", type text}, {"calculated_host_listings_count", Int64.Type}, {"availability_365", Int64.Type}, {"", Int64.Type}}),
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each [id] <> null and [id] <> ""),
				    #"Filas filtradas1" = Table.SelectRows(#"Filas filtradas", each [host_id] <> null and [host_id] <> ""),
				    #"Filas filtradas2" = Table.SelectRows(#"Filas filtradas1", each [host_name] <> null and [host_name] <> ""),
				    #"Errores quitados" = Table.RemoveRowsWithErrors(#"Filas filtradas2", {"longitude"}),
				    #"Filas filtradas3" = Table.SelectRows(#"Errores quitados", each [last_review] <> null and [last_review] <> ""),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Filas filtradas3",{""}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columnas quitadas",{{"longitude", Int64.Type}, {"latitude", Int64.Type}, {"price", Currency.Type}}),
				    #"Filas filtradas4" = Table.SelectRows(#"Tipo cambiado1", each ([id] <> "HISTORICAL")),
				    #"Personalizada agregada" = Table.AddColumn(#"Filas filtradas4", "name_limpio", each Text.Select([name], {"A".."Z", "a".."z", "0".."9", " ", ".", ",", "-", "ñ", "Ñ", "á", "é", "í", "ó", "ú", "Á", "É", "Í", "Ó", "Ú", "&"})),
				    #"Columnas reordenadas" = Table.ReorderColumns(#"Personalizada agregada",{"id", "name", "name_limpio", "host_id", "host_name", "neighbourhood_group", "neighbourhood", "latitude", "longitude", "room_type", "price", "minimum_nights", "number_of_reviews", "last_review", "reviews_per_month", "calculated_host_listings_count", "availability_365"}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columnas reordenadas",{{"last_review", type date}})
				in
				    #"Tipo cambiado2"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

