table milan_airbnb
	lineageTag: 7eb91f14-6100-4cd2-a644-ce5e7369c16b

	column id
		dataType: string
		lineageTag: 896cb956-e682-4cf6-8399-b81a9232e5c0
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 02fb3602-ba4a-42b3-a92b-43ef42f4de3e
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column host_id
		dataType: string
		lineageTag: 3ac5db78-d626-4c2f-bc3a-dc239d246ab9
		summarizeBy: none
		sourceColumn: host_id

		annotation SummarizationSetBy = Automatic

	column host_name
		dataType: string
		lineageTag: 7097674b-111f-4efb-9e7a-ae0418716fcd
		summarizeBy: none
		sourceColumn: host_name

		annotation SummarizationSetBy = Automatic

	column neighbourhood
		dataType: string
		lineageTag: 03a182ac-43f9-4855-83a9-3bcc37402208
		summarizeBy: none
		sourceColumn: neighbourhood

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: int64
		formatString: 0
		lineageTag: 8e708efa-32c3-43f0-a7d3-5b8bf22ffb0a
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: int64
		formatString: 0
		lineageTag: 2873bc9f-a904-4a18-8e25-1feb6529ffbd
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

	column room_type
		dataType: string
		lineageTag: 45cbb56c-98a6-451f-94ac-5cc7f0128f82
		summarizeBy: none
		sourceColumn: room_type

		annotation SummarizationSetBy = Automatic

	column price
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 142cdfbb-9dd1-49ea-9118-bfa5cba9a35f
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column minimum_nights
		dataType: int64
		formatString: 0
		lineageTag: 0196e59a-2da9-41f6-8632-67241ba41bc3
		summarizeBy: sum
		sourceColumn: minimum_nights

		annotation SummarizationSetBy = Automatic

	column number_of_reviews
		dataType: int64
		formatString: 0
		lineageTag: 2e45438a-9bd2-47a4-8a33-4e3dc7a9aca7
		summarizeBy: sum
		sourceColumn: number_of_reviews

		annotation SummarizationSetBy = Automatic

	column last_review
		dataType: dateTime
		formatString: Long Date
		lineageTag: fae33794-be1a-4260-a28b-441e48cb538f
		summarizeBy: none
		sourceColumn: last_review

		variation Variación
			isDefault
			relationship: 4ae7a358-5006-4c9c-af4b-5c67cb6374e9
			defaultHierarchy: LocalDateTable_3e1fe1e5-bdff-480c-ba5e-52e0409b49df.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column reviews_per_month
		dataType: int64
		formatString: 0
		lineageTag: f1d7e8c7-57a8-40ec-a421-da456f5ba3ab
		summarizeBy: sum
		sourceColumn: reviews_per_month

		annotation SummarizationSetBy = Automatic

	column calculated_host_listings_count
		dataType: int64
		formatString: 0
		lineageTag: 0275c519-9235-4660-9843-2d68beea50c0
		summarizeBy: sum
		sourceColumn: calculated_host_listings_count

		annotation SummarizationSetBy = Automatic

	column availability_365
		dataType: int64
		formatString: 0
		lineageTag: b1921458-4b6c-4c47-a5a0-0a3da31db300
		summarizeBy: sum
		sourceColumn: availability_365

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 2379457b-bf50-46ad-9ab3-e55e2833e5f4
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	partition milan_airbnb = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\ritar\Documents\PROYECTOS\DA-project-Power-BI-Analysis-Grupo-5\Data\milan_airbnb.csv"),[Delimiter=",", Columns=15, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"name", type text}, {"host_id", Int64.Type}, {"host_name", type text}, {"neighbourhood", type text}, {"latitude", Int64.Type}, {"longitude", Int64.Type}, {"room_type", type text}, {"price", Int64.Type}, {"minimum_nights", Int64.Type}, {"number_of_reviews", Int64.Type}, {"last_review", type date}, {"reviews_per_month", Int64.Type}, {"calculated_host_listings_count", Int64.Type}, {"availability_365", Int64.Type}}),
				    #"Errores quitados" = Table.RemoveRowsWithErrors(#"Tipo cambiado"),
				    #"Duplicados quitados" = Table.Distinct(#"Errores quitados"),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Duplicados quitados", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Filas en blanco eliminadas",{{"id", type text}, {"name", type text}, {"host_id", type text}, {"host_name", type text}, {"neighbourhood", type text}, {"room_type", type text}}),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Tipo cambiado1",{{"id", Text.Proper, type text}, {"name", Text.Proper, type text}, {"host_id", Text.Proper, type text}, {"host_name", Text.Proper, type text}, {"neighbourhood", Text.Proper, type text}, {"room_type", Text.Proper, type text}}),
				    #"Texto limpio" = Table.TransformColumns(#"Poner En Mayúsculas Cada Palabra",{{"id", Text.Clean, type text}, {"name", Text.Clean, type text}, {"host_id", Text.Clean, type text}, {"host_name", Text.Clean, type text}, {"neighbourhood", Text.Clean, type text}, {"room_type", Text.Clean, type text}}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Texto limpio",{{"price", Currency.Type}}),
				    #"Filas en blanco eliminadas1" = Table.SelectRows(#"Tipo cambiado2", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Filas en blanco eliminadas2" = Table.SelectRows(#"Filas en blanco eliminadas1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Filas filtradas" = Table.SelectRows(#"Filas en blanco eliminadas2", each [last_review] <> null and [last_review] <> ""),
				    #"Added Custom" = Table.AddColumn(#"Filas filtradas", "city", each "Milan")
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

