table NY_airbnb
	lineageTag: 32ecd945-f0b3-4f52-ba1f-db9af1d396e4

	column id
		dataType: string
		lineageTag: d3f25c63-d455-4332-8b7d-783c8a724c35
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 737b2392-7ef8-49fe-93f4-1e4b2e4b6d5f
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column host_id
		dataType: string
		lineageTag: 74faa5eb-ae48-42dc-bd10-83979d430917
		summarizeBy: none
		sourceColumn: host_id

		annotation SummarizationSetBy = Automatic

	column host_name
		dataType: string
		lineageTag: f1cceaf3-5cd4-4bf2-ad67-cba7ec5299ad
		summarizeBy: none
		sourceColumn: host_name

		annotation SummarizationSetBy = Automatic

	column neighbourhood_group
		dataType: string
		lineageTag: 61ef588c-a6dc-4bbe-b2ae-1ac969abec47
		summarizeBy: none
		sourceColumn: neighbourhood_group

		annotation SummarizationSetBy = Automatic

	column neighbourhood
		dataType: string
		lineageTag: 550ef487-dc02-4bf8-9b0f-579ed2630381
		summarizeBy: none
		sourceColumn: neighbourhood

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: int64
		formatString: 0
		lineageTag: bf71c4b6-2317-41f5-b91a-c44ec65d9ff0
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: int64
		formatString: 0
		lineageTag: 2ad0f5e1-7f94-4809-83d6-1d1354658ad1
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

	column room_type
		dataType: string
		lineageTag: 15f06d6b-d278-42e5-a326-dca6203ff1aa
		summarizeBy: none
		sourceColumn: room_type

		annotation SummarizationSetBy = Automatic

	column price
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 56f1ed00-877d-48ea-b611-490d292146a0
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column minimum_nights
		dataType: int64
		formatString: 0
		lineageTag: b6614106-4f09-42dd-82ff-37eb7f73a62b
		summarizeBy: sum
		sourceColumn: minimum_nights

		annotation SummarizationSetBy = Automatic

	column number_of_reviews
		dataType: int64
		formatString: 0
		lineageTag: de36274c-b98e-4f43-986f-4a735626003c
		summarizeBy: sum
		sourceColumn: number_of_reviews

		annotation SummarizationSetBy = Automatic

	column last_review
		dataType: dateTime
		formatString: Long Date
		lineageTag: aef37f79-8a81-4c0d-8019-ef8e4abe9f77
		summarizeBy: none
		sourceColumn: last_review

		variation Variación
			isDefault
			relationship: e681c884-b4e8-4d73-a863-482118dfae28
			defaultHierarchy: LocalDateTable_e59332f3-c2bb-43e8-bc07-8fba30d62600.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column reviews_per_month
		dataType: int64
		formatString: 0
		lineageTag: a3e0f4fa-29d4-4bfb-967e-9812831e0e85
		summarizeBy: sum
		sourceColumn: reviews_per_month

		annotation SummarizationSetBy = Automatic

	column calculated_host_listings_count
		dataType: int64
		formatString: 0
		lineageTag: 54237828-dce7-4c74-a027-c5300b63630c
		summarizeBy: sum
		sourceColumn: calculated_host_listings_count

		annotation SummarizationSetBy = Automatic

	column availability_365
		dataType: int64
		formatString: 0
		lineageTag: 1c9b305e-43a7-4019-a035-ec86ff72dc24
		summarizeBy: sum
		sourceColumn: availability_365

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: f613ae6f-0a93-4056-b77a-680762dc8448
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column name_limpio
		dataType: string
		lineageTag: 44580660-b6f3-4e00-95ef-4e7aeea1cf57
		summarizeBy: none
		sourceColumn: name_limpio

		annotation SummarizationSetBy = Automatic

	partition NY_airbnb = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\Don Bosco\Desktop\bootcamp-da-p2\DA-project-Power-BI-Analysis-Grupo-5\Data\NY_airbnb.csv"),[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"name", type text}, {"host_id", Int64.Type}, {"host_name", type text}, {"neighbourhood_group", type text}, {"neighbourhood", type text}, {"latitude", Int64.Type}, {"longitude", Int64.Type}, {"room_type", type text}, {"price", Int64.Type}, {"minimum_nights", Int64.Type}, {"number_of_reviews", Int64.Type}, {"last_review", type date}, {"reviews_per_month", Int64.Type}, {"calculated_host_listings_count", Int64.Type}, {"availability_365", Int64.Type}}),
				    #"Errores quitados" = Table.RemoveRowsWithErrors(#"Tipo cambiado"),
				    #"Duplicados quitados" = Table.Distinct(#"Errores quitados"),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Duplicados quitados", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Filas en blanco eliminadas",{{"id", type text}, {"host_id", Int64.Type}, {"price", Currency.Type}}),
				    #"Filas en blanco eliminadas1" = Table.SelectRows(#"Tipo cambiado1", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Filas en blanco eliminadas1",{{"last_review", type date}}),
				    Personalizado1 = #"Tipo cambiado2",
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(Table.TransformColumnTypes(Personalizado1, {{"host_id", type text}}, "es-ES"),{{"id", Text.Proper, type text}, {"name", Text.Proper, type text}, {"host_id", Text.Proper, type text}, {"host_name", Text.Proper, type text}, {"neighbourhood_group", Text.Proper, type text}, {"neighbourhood", Text.Proper, type text}, {"room_type", Text.Proper, type text}}),
				    #"Texto limpio" = Table.TransformColumns(#"Poner En Mayúsculas Cada Palabra",{{"id", Text.Clean, type text}, {"name", Text.Clean, type text}, {"host_id", Text.Clean, type text}, {"host_name", Text.Clean, type text}, {"neighbourhood_group", Text.Clean, type text}, {"neighbourhood", Text.Clean, type text}, {"room_type", Text.Clean, type text}}),
				    #"Added Custom" = Table.AddColumn(#"Texto limpio", "city", each "NY"),
				    #"Personalizada agregada" = Table.AddColumn(#"Added Custom", "name_limpio", each Text.Select([name], {"A".."Z", "a".."z", "0".."9", " ", ".", ",", "-", "ñ", "Ñ", "á", "é", "í", "ó", "ú", "Á", "É", "Í", "Ó", "Ú", "&"}))
				in
				    #"Personalizada agregada"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

