table sydney_airbnb
	lineageTag: 6913e9b8-7351-48eb-ade3-435e315ac586

	column id
		dataType: int64
		formatString: 0
		lineageTag: 5facc673-4fa2-47d6-81d5-bcefe6ca233c
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: c9328259-2019-41d3-974a-336b3ecb1a9c
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column host_id
		dataType: int64
		formatString: 0
		lineageTag: a9ad21f3-cbae-4f04-b9bc-78f50c6b5091
		summarizeBy: sum
		sourceColumn: host_id

		annotation SummarizationSetBy = Automatic

	column host_name
		dataType: string
		lineageTag: 211d60e8-bed1-43e1-abc4-d95b07efa652
		summarizeBy: none
		sourceColumn: host_name

		annotation SummarizationSetBy = Automatic

	column neighbourhood_group
		dataType: string
		lineageTag: faf17444-cb40-46d1-836b-19c851f2d944
		summarizeBy: none
		sourceColumn: neighbourhood_group

		annotation SummarizationSetBy = Automatic

	column neighbourhood
		dataType: string
		lineageTag: 31f6e3f6-1a8d-4378-9a6a-99692ff45598
		summarizeBy: none
		sourceColumn: neighbourhood

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 2cf0adfa-8703-4137-b378-c072dc955cba
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 0c8bc62a-41c5-4d9f-ab71-2f52783d425e
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column room_type
		dataType: string
		lineageTag: 3f259e63-3d1e-4964-bc7a-efcf52872d39
		summarizeBy: none
		sourceColumn: room_type

		annotation SummarizationSetBy = Automatic

	column price
		dataType: int64
		formatString: 0
		lineageTag: 9527dc4f-0d10-408b-bb7c-9da66cfb39b7
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	column minimum_nights
		dataType: int64
		formatString: 0
		lineageTag: c8759991-0534-4204-bd01-b3be442c7069
		summarizeBy: sum
		sourceColumn: minimum_nights

		annotation SummarizationSetBy = Automatic

	column number_of_reviews
		dataType: int64
		formatString: 0
		lineageTag: 855a7637-594a-413a-914b-049705d74890
		summarizeBy: sum
		sourceColumn: number_of_reviews

		annotation SummarizationSetBy = Automatic

	column last_review
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5f41d4a4-84a8-4f45-99f1-9798f3c963ef
		summarizeBy: none
		sourceColumn: last_review

		variation Variación
			isDefault
			relationship: c6ed420f-43d3-4a46-ab4c-01872f228558
			defaultHierarchy: LocalDateTable_80ae01ff-1d34-4d20-a128-164f50731ceb.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column reviews_per_month
		dataType: int64
		formatString: 0
		lineageTag: 3a1a100e-b655-42f2-8ffb-dc6583680280
		summarizeBy: sum
		sourceColumn: reviews_per_month

		annotation SummarizationSetBy = Automatic

	column calculated_host_listings_count
		dataType: int64
		formatString: 0
		lineageTag: d7ea8dd9-8e74-4db2-9945-80ee5e623949
		summarizeBy: sum
		sourceColumn: calculated_host_listings_count

		annotation SummarizationSetBy = Automatic

	column availability_365
		dataType: int64
		formatString: 0
		lineageTag: 68e7b528-548a-4d7e-b4d8-3075452fb201
		summarizeBy: sum
		sourceColumn: availability_365

		annotation SummarizationSetBy = Automatic

	column ciudad
		dataType: string
		lineageTag: 62dbaf51-cb47-49b4-95fb-9e0c898b445d
		summarizeBy: none
		sourceColumn: ciudad

		annotation SummarizationSetBy = Automatic

	column name_limpio
		dataType: string
		lineageTag: 09b2a212-6f35-4fea-ae01-a8003feed16d
		summarizeBy: none
		sourceColumn: name_limpio

		annotation SummarizationSetBy = Automatic

	partition sydney_airbnb = m
		mode: import
		source = ```
				let
				    // NOTA: Reemplaza esta línea de "Origen" por la tuya original si la ruta de tu archivo es diferente
				    Origen = Csv.Document(File.Contents("C:\Users\Don Bosco\Desktop\bootcamp-da-p2\DA-project-Power-BI-Analysis-Grupo-5\Data\sydney_airbnb.csv"),[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    
				    // 1. Promover los encabezados del CSV
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				
				    // 2. Convertir Latitud usando región de EE.UU. (acepta puntos como decimales)
				    #"Tipo cambiado con configuración regional" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"latitude", type number}}, "en-US"),
				
				    // 3. Si la latitud dio error (como "Waverley"), se reemplaza por un 0
				    #"Errores reemplazados" = Table.ReplaceErrorValues(#"Tipo cambiado con configuración regional", {{"latitude", 0}}),
				
				    // 4. Convertir Longitud usando región de EE.UU.
				    #"Tipo cambiado con configuración regional1" = Table.TransformColumnTypes(#"Errores reemplazados", {{"longitude", type number}}, "en-US"),
				
				    // 5. Si la longitud dio error, se reemplaza por un 0
				    #"Errores reemplazados1" = Table.ReplaceErrorValues(#"Tipo cambiado con configuración regional1", {{"longitude", 0}}),
				
				    // 6. Limpieza de textos en un solo paso eficiente (Poner en mayúscula cada palabra, quitar espacios y caracteres invisibles)
				    #"Textos limpios" = Table.TransformColumns(#"Errores reemplazados1", {
				        {"name", each Text.Proper(Text.Trim(Text.Clean(Text.From(_)))), type text},
				        {"host_name", each Text.Proper(Text.Trim(Text.Clean(Text.From(_)))), type text},
				        {"neighbourhood", each Text.Proper(Text.Trim(Text.Clean(Text.From(_)))), type text},
				        {"room_type", each Text.Proper(Text.Trim(Text.Clean(Text.From(_)))), type text}
				    }),
				
				    // 7. Convertir columnas numéricas de manera segura (si encuentra texto pone NULL) y limpiar el signo $ y comas del precio
				    #"room_type" = Table.TransformColumns(#"Textos limpios", {
				        {"availability_365", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"calculated_host_listings_count", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"number_of_reviews", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"minimum_nights", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"price", each try Int64.From(Text.Replace(Text.Replace(Text.Replace(Text.Trim(Text.From(_)), "$", ""), ",", ""), ".", "")) otherwise null, Int64.Type},
				        {"host_id", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type},
				        {"id", each try Int64.From(Text.Trim(Text.From(_))) otherwise null, Int64.Type}
				    }),
				
				    // 8. Convertir reseñas por mes usando región de EE.UU.
				    #"Tipo_EEUU_reviews_per_month" = Table.TransformColumnTypes(#"room_type", {{"reviews_per_month", type number}}, "en-US"),
				
				    // 9. Si la reseña da error, se reemplaza por 0
				    #"Errores_reviews_per_month" = Table.ReplaceErrorValues(#"Tipo_EEUU_reviews_per_month", {{"reviews_per_month", 0}}),
				
				    // 10. Convertir las reseñas finales a número entero
				    #"tipo-entero_reviews_per_month" = Table.TransformColumnTypes(#"Errores_reviews_per_month", {{"reviews_per_month", Int64.Type}}),
				
				    // 11. Convertir de manera segura la columna de fechas (si falla pone NULL)
				    #"Tipo cambiado" = Table.TransformColumns(#"tipo-entero_reviews_per_month", {
				        {"last_review", each try Date.From(_) otherwise null, type date}
				    }),
				
				    // 12. Agregar la columna final identificando que pertenece a la ciudad de sydney
				    #"Columna ciudad agregada" = Table.AddColumn(#"Tipo cambiado", "ciudad", each "sydney", type text),
				    Personalizado1 = Table.AddColumn(#"Columna ciudad agregada", "name_limpio", each Text.Select([name], {"A".."Z", "a".."z", "0".."9", " ", ".", ",", "-", "ñ", "Ñ", "á", "é", "í", "ó", "ú", "Á", "É", "Í", "Ó", "Ú", "&"}))
				in
				    Personalizado1
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

