table tokyo_airbnb
	lineageTag: 45222da6-f510-4835-8948-a2af2e36acd1

	column id
		dataType: int64
		formatString: 0
		lineageTag: 248741d0-b507-4aee-868a-fbe34b956f53
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: e652fcbe-64f1-48bb-87c1-3e1fc380e030
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column host_id
		dataType: int64
		formatString: 0
		lineageTag: c670a404-dbcc-4c25-95c5-9df39553635b
		summarizeBy: sum
		sourceColumn: host_id

		annotation SummarizationSetBy = Automatic

	column host_name
		dataType: string
		lineageTag: 55134ce8-7c4d-421a-bceb-b17313f991cc
		summarizeBy: none
		sourceColumn: host_name

		annotation SummarizationSetBy = Automatic

	column neighbourhood
		dataType: string
		lineageTag: 786e5393-69ee-46c1-8324-2f865b0f2514
		summarizeBy: none
		sourceColumn: neighbourhood

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: int64
		formatString: 0
		lineageTag: 6c7992ba-9dff-4011-8c55-23b1b351560b
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: int64
		formatString: 0
		lineageTag: 725c509c-4d8d-4f37-abb5-03e7e5efb039
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

	column room_type
		dataType: string
		lineageTag: f289bc1f-5354-4c95-97ed-09fde03c1eac
		summarizeBy: none
		sourceColumn: room_type

		annotation SummarizationSetBy = Automatic

	column price
		dataType: int64
		formatString: 0
		lineageTag: 35324553-1e80-490a-b2ce-223555e942b5
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	column minimum_nights
		dataType: int64
		formatString: 0
		lineageTag: 635c34e8-4887-4cd4-8d1a-1849a67a5569
		summarizeBy: sum
		sourceColumn: minimum_nights

		annotation SummarizationSetBy = Automatic

	column number_of_reviews
		dataType: int64
		formatString: 0
		lineageTag: cfa77f28-e8ed-419c-b301-26fc538aa08e
		summarizeBy: sum
		sourceColumn: number_of_reviews

		annotation SummarizationSetBy = Automatic

	column last_review
		dataType: dateTime
		formatString: Long Date
		lineageTag: d5608417-36e8-48fe-964b-19263454e5d3
		summarizeBy: none
		sourceColumn: last_review

		variation Variación
			isDefault
			relationship: fd80cb00-d0ef-41bf-afcf-80b674b69721
			defaultHierarchy: LocalDateTable_92649bbc-6abd-4e31-9543-2dc654dfd80f.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column reviews_per_month
		dataType: int64
		formatString: 0
		lineageTag: c680f48c-b237-4d6a-973d-544d3ba7167d
		summarizeBy: sum
		sourceColumn: reviews_per_month

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 23508e5c-c02a-4bd0-9e98-23d70c3f59b5
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column name_limpio
		dataType: string
		lineageTag: e2bc09e3-12ef-480e-925a-6b7cf0875068
		summarizeBy: none
		sourceColumn: name_limpio

		annotation SummarizationSetBy = Automatic

	column availability_365
		dataType: int64
		formatString: 0
		lineageTag: caab1253-de3d-4921-86ce-5c3d1a14e61f
		summarizeBy: sum
		sourceColumn: availability_365

		annotation SummarizationSetBy = Automatic

	column neighbourhood_group
		dataType: string
		lineageTag: 07043a08-c37a-4caf-9e1e-23710325cc20
		summarizeBy: none
		sourceColumn: neighbourhood_group

		annotation SummarizationSetBy = Automatic

	column calculated_host_listings_count
		dataType: string
		lineageTag: c041660d-e31a-4601-975a-11bad17c3962
		summarizeBy: none
		sourceColumn: calculated_host_listings_count

		annotation SummarizationSetBy = Automatic

	partition tokyo_airbnb = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\crist\Desktop\DataAnalyst_Ana\DA-project-Power-BI-Analysis-Grupo-5\data\tokyo_airbnb.csv"),[Delimiter=",", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"name", type text}, {"host_id", Int64.Type}, {"host_name", type text}, {"neighbourhood_group", type text}, {"neighbourhood", type text}, {"latitude", Int64.Type}, {"longitude", Int64.Type}, {"room_type", type text}, {"price", Int64.Type}, {"minimum_nights", Int64.Type}, {"number_of_reviews", Int64.Type}, {"last_review", type date}, {"reviews_per_month", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Tipo cambiado", "city", each "Tokyo"),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Added Custom", {"id"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Errors", each [host_id] <> null and [host_id] <> ""),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each [host_name] <> null and [host_name] <> ""),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows1",{"neighbourhood_group"}),
				    #"Filtered Rows2" = Table.SelectRows(#"Removed Columns", each [last_review] <> null and [last_review] <> ""),
				    #"Personalizada agregada" = Table.AddColumn(#"Filtered Rows2", "name_limpio", each Text.Select([name], {"A".."Z", "a".."z", "0".."9", " ", ".", ",", "-", "ñ", "Ñ", "á", "é", "í", "ó", "ú", "Á", "É", "Í", "Ó", "Ú", "&"})),
				    #"Personalizada agregada1" = Table.AddColumn(#"Personalizada agregada", "availability_365", each 0),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada1",{{"availability_365", Int64.Type}}),
				    #"Personalizada agregada2" = Table.AddColumn(#"Tipo cambiado1", "neighbourhood_group", each null),
				    #"Personalizada agregada3" = Table.AddColumn(#"Personalizada agregada2", "calculated_host_listings_count", each null)
				in
				    #"Personalizada agregada3"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

