table tokyo_airbnb
	lineageTag: 9d4e8946-261b-4c4a-ad06-304ca07ae436

	column id
		dataType: int64
		formatString: 0
		lineageTag: a8f31ef2-16ee-4fab-b01c-6e62d5bf62c1
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 103bc8e3-57ef-4ee6-b658-59a26d4435fb
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column host_id
		dataType: int64
		formatString: 0
		lineageTag: 247f5cf3-a654-498d-bb04-950d614ffe3a
		summarizeBy: sum
		sourceColumn: host_id

		annotation SummarizationSetBy = Automatic

	column host_name
		dataType: string
		lineageTag: a3e3178a-d286-42ff-9f77-c5a4ab05e60c
		summarizeBy: none
		sourceColumn: host_name

		annotation SummarizationSetBy = Automatic

	column neighbourhood
		dataType: string
		lineageTag: 605e7dd6-e4e9-4772-91f1-41160915d84b
		summarizeBy: none
		sourceColumn: neighbourhood

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: int64
		formatString: 0
		lineageTag: 8e4e4147-8eaf-499d-81c8-557252496d90
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: int64
		formatString: 0
		lineageTag: c44c0d89-09b6-4e94-b3c9-3cfa4e3d1d52
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

	column room_type
		dataType: string
		lineageTag: 68c9e9f6-a2a3-45ce-9f71-33c1bfe7524a
		summarizeBy: none
		sourceColumn: room_type

		annotation SummarizationSetBy = Automatic

	column price
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: e0af2db4-6479-4b04-86f3-67a2912a3d8d
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column minimum_nights
		dataType: int64
		formatString: 0
		lineageTag: 545ac1fa-4b6f-4e24-a5e8-d5247d35e7e8
		summarizeBy: sum
		sourceColumn: minimum_nights

		annotation SummarizationSetBy = Automatic

	column number_of_reviews
		dataType: int64
		formatString: 0
		lineageTag: 8b74e226-3e7f-47b1-b5d9-b3d46971e0c1
		summarizeBy: sum
		sourceColumn: number_of_reviews

		annotation SummarizationSetBy = Automatic

	column last_review
		dataType: dateTime
		formatString: Long Date
		lineageTag: d348ce8a-1984-4a4e-9cec-47f8616ec937
		summarizeBy: none
		sourceColumn: last_review

		variation Variación
			isDefault
			relationship: e6898f1d-d0d4-4383-b01f-94b43a2b7b18
			defaultHierarchy: LocalDateTable_4c223b52-058f-42ac-9d79-1676211a83b3.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column reviews_per_month
		dataType: int64
		formatString: 0
		lineageTag: cbf1596f-6404-489a-a93d-e0065615fd58
		summarizeBy: sum
		sourceColumn: reviews_per_month

		annotation SummarizationSetBy = Automatic

	partition tokyo_airbnb = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\ritar\Documents\PROYECTOS\DA-project-Power-BI-Analysis-Grupo-5\Data\tokyo_airbnb.csv"),[Delimiter=",", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"name", type text}, {"host_id", Int64.Type}, {"host_name", type text}, {"neighbourhood_group", type text}, {"neighbourhood", type text}, {"latitude", Int64.Type}, {"longitude", Int64.Type}, {"room_type", type text}, {"price", Int64.Type}, {"minimum_nights", Int64.Type}, {"number_of_reviews", Int64.Type}, {"last_review", type date}, {"reviews_per_month", Int64.Type}}),
				    #"Errores quitados" = Table.RemoveRowsWithErrors(#"Tipo cambiado", {"id"}),
				    #"Filas filtradas" = Table.SelectRows(#"Errores quitados", each [host_id] <> null and [host_id] <> ""),
				    #"Filas filtradas1" = Table.SelectRows(#"Filas filtradas", each [host_name] <> null and [host_name] <> ""),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Filas filtradas1",{"neighbourhood_group"}),
				    #"Filas filtradas2" = Table.SelectRows(#"Columnas quitadas", each [last_review] <> null and [last_review] <> ""),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Filas filtradas2",{{"price", Currency.Type}})
				in
				    #"Tipo cambiado1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

