table sydney_airbnb
	lineageTag: 03ea6e60-7d3b-4d09-b124-66cb11716b1e

	column id
		dataType: string
		lineageTag: 2a1b6cb7-4cb4-4e7c-b0a7-a108af1b96f2
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: e4075296-25e5-4fc6-afaa-92ad2139f084
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column host_id
		dataType: string
		lineageTag: c3046778-6554-4384-92d3-2080e2725c33
		summarizeBy: none
		sourceColumn: host_id

		annotation SummarizationSetBy = Automatic

	column host_name
		dataType: string
		lineageTag: 715727a7-5c2b-4a1a-862c-18ce86c71e2b
		summarizeBy: none
		sourceColumn: host_name

		annotation SummarizationSetBy = Automatic

	column neighbourhood
		dataType: string
		lineageTag: dbbc6445-9ab7-4245-9a04-174ecee74ffa
		summarizeBy: none
		sourceColumn: neighbourhood

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: int64
		formatString: 0
		lineageTag: 65a491c9-98ca-4fe4-80b0-ed15f1563867
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: int64
		formatString: 0
		lineageTag: a2315a7f-531f-42d9-9032-245a492d7c4b
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

	column room_type
		dataType: string
		lineageTag: 5d2c60b4-4e6b-409c-934e-5b7f5cec04c5
		summarizeBy: none
		sourceColumn: room_type

		annotation SummarizationSetBy = Automatic

	column price
		dataType: int64
		formatString: 0
		lineageTag: 05570feb-7b0d-4716-927e-427538db2796
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	column minimum_nights
		dataType: int64
		formatString: 0
		lineageTag: 83e9fb5c-e963-4776-90f2-e902cda95a55
		summarizeBy: sum
		sourceColumn: minimum_nights

		annotation SummarizationSetBy = Automatic

	column number_of_reviews
		dataType: int64
		formatString: 0
		lineageTag: 749dc24c-bcbc-46a0-8eee-50169d73679a
		summarizeBy: sum
		sourceColumn: number_of_reviews

		annotation SummarizationSetBy = Automatic

	column last_review
		dataType: dateTime
		formatString: Long Date
		lineageTag: f11d762e-464e-4556-a491-6d79e4102ce1
		summarizeBy: none
		sourceColumn: last_review

		variation Variación
			isDefault
			relationship: 7b1d7872-2b8e-4473-bc07-a604c693f5ff
			defaultHierarchy: LocalDateTable_d57a3193-9309-45c9-86d2-9febe055fcfc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column reviews_per_month
		dataType: int64
		formatString: 0
		lineageTag: c485046d-3c0d-4659-bebd-e5fabdb6dbf2
		summarizeBy: sum
		sourceColumn: reviews_per_month

		annotation SummarizationSetBy = Automatic

	column calculated_host_listings_count
		dataType: int64
		formatString: 0
		lineageTag: 9ebd2ef5-4c2b-4c75-bb4b-c76a320b17fe
		summarizeBy: sum
		sourceColumn: calculated_host_listings_count

		annotation SummarizationSetBy = Automatic

	column availability_365
		dataType: int64
		formatString: 0
		lineageTag: 3b403e85-c2ad-40bc-8109-cca74eb42f07
		summarizeBy: sum
		sourceColumn: availability_365

		annotation SummarizationSetBy = Automatic

	column 'id.1'
		dataType: int64
		formatString: 0
		lineageTag: 7accf714-8735-46d1-9f2b-30efe0c29d2a
		summarizeBy: sum
		sourceColumn: id.1

		annotation SummarizationSetBy = Automatic

	partition sydney_airbnb = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\ritar\Documents\PROYECTOS\DA-project-Power-BI-Analysis-Grupo-5\Data\sydney_airbnb.csv"),[Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Filas filtradas" = Table.SelectRows(#"Encabezados promovidos", each [name] <> null and [name] <> ""),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Filas filtradas",{"neighbourhood_group"}),
				    #"Filas filtradas1" = Table.SelectRows(#"Columnas quitadas", each [reviews_per_month] <> null and [reviews_per_month] <> ""),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Filas filtradas1",{{"latitude", Int64.Type}, {"longitude", Int64.Type}, {"price", Int64.Type}, {"minimum_nights", Int64.Type}, {"number_of_reviews", Int64.Type}, {"last_review", type date}, {"reviews_per_month", Int64.Type}, {"calculated_host_listings_count", Int64.Type}, {"availability_365", Int64.Type}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Tipo cambiado", "id.1", each Text.Select([id], {"0".."9"})),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"id.1", Int64.Type}, {"longitude", Int64.Type}}),
				    #"Errores quitados" = Table.RemoveRowsWithErrors(#"Tipo cambiado1", {"id"}),
				    #"Errores quitados1" = Table.RemoveRowsWithErrors(#"Errores quitados", {"name"}),
				    #"Errores quitados2" = Table.RemoveRowsWithErrors(#"Errores quitados1", {"host_id"}),
				    #"Errores quitados3" = Table.RemoveRowsWithErrors(#"Errores quitados2", {"host_name"}),
				    #"Errores quitados4" = Table.RemoveRowsWithErrors(#"Errores quitados3", {"neighbourhood"}),
				    #"Errores quitados5" = Table.RemoveRowsWithErrors(#"Errores quitados4", {"latitude"}),
				    #"Errores quitados6" = Table.RemoveRowsWithErrors(#"Errores quitados5", {"longitude"}),
				    #"Errores quitados7" = Table.RemoveRowsWithErrors(#"Errores quitados6", {"room_type"}),
				    #"Errores quitados8" = Table.RemoveRowsWithErrors(#"Errores quitados7", {"price"}),
				    #"Errores quitados9" = Table.RemoveRowsWithErrors(#"Errores quitados8", {"minimum_nights"}),
				    #"Errores quitados10" = Table.RemoveRowsWithErrors(#"Errores quitados9", {"number_of_reviews"}),
				    #"Errores quitados11" = Table.RemoveRowsWithErrors(#"Errores quitados10", {"last_review"}),
				    #"Errores quitados12" = Table.RemoveRowsWithErrors(#"Errores quitados11", {"reviews_per_month"}),
				    #"Errores quitados13" = Table.RemoveRowsWithErrors(#"Errores quitados12", {"reviews_per_month"}),
				    #"Errores quitados14" = Table.RemoveRowsWithErrors(#"Errores quitados13", {"calculated_host_listings_count"}),
				    #"Errores quitados15" = Table.RemoveRowsWithErrors(#"Errores quitados14", {"availability_365"}),
				    #"Errores quitados16" = Table.RemoveRowsWithErrors(#"Errores quitados15", {"id.1"})
				in
				    #"Errores quitados16"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

